
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
/* 999999999 */
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:53a0049c-072d-4637-9ce2-0152195d8c1b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6dMXOwTaM",
    "aws_user_pools_web_client_id": "1c11ev3jdqjlucgemphojv1en6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qe2eww72arewhnbzfn7hm2ntey.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oepsthqynrbohju4qk5kgtcdxi",
    "aws_user_files_s3_bucket": "awsbackend5b1ae1dc83204fc88a9df10e7ed4933c85132-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
